# Generated by Django 5.1.6 on 2025-02-16 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Chirps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chirp_body', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField()),
                ('parent_chirp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chirper.chirps')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chirper.users')),
            ],
        ),
    ]
