# Generated by Django 5.1.6 on 2025-02-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirps',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
