# Generated by Django 5.1.6 on 2025-03-13 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirps',
            name='parent_chirp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='chirper.chirps'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='chirp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chirper.chirps'),
        ),
    ]
