# Generated by Django 5.1.6 on 2025-03-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0002_alter_chirps_parent_chirp_alter_reply_chirp'),
    ]

    operations = [
        migrations.RenameModel("Chirps", "Chirp")
    ]
