# Generated by Django 5.1.6 on 2025-03-06 03:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0002_alter_chirps_user_id_reply_userfollowing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.AddField(
            model_name='chirps',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_chirps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chirps',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chirps',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chirps', to=settings.AUTH_USER_MODEL),
        ),
    ]
