# Generated by Django 5.1.6 on 2025-02-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0002_chirps_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirps',
            name='likes',
        ),
    ]
