# Generated by Django 5.1.6 on 2025-03-08 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0003_rename_created_at_reply_created_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reply_chirps', to=settings.AUTH_USER_MODEL),
        ),
    ]
