# Generated by Django 5.1.6 on 2025-03-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0003_remove_chirps_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirps',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
