# Generated by Django 5.1.6 on 2025-03-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0004_chirps_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirps',
            name='likes',
        ),
        migrations.AddField(
            model_name='chirps',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_chirps', to='chirper.users'),
        ),
    ]
