# Generated by Django 5.1.6 on 2025-03-05 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0005_remove_chirps_likes_chirps_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirps',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chirps',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_chirps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chirps',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
