# Generated by Django 5.1.6 on 2025-03-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0002_alter_chirps_user_id_reply_userfollowing_and_more'),
        ('chirper', '0007_alter_chirps_user_id'),
    ]

    operations = [
    ]
