# Generated by Django 5.1.6 on 2025-03-06 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0009_users_alter_chirps_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reply_chirps', to=settings.AUTH_USER_MODEL),
        ),
    ]
